spring:
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: provider
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://120.78.174.107:2181
    server: true
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20880

server:
  port: 9090
